Repository WebXDAO/WebXDAO.github.io, pull requests merged in 2021-09, with the labels that each got.

#2 Added PR template
  .github/pull_request_template.md
Labels: enhancement

#4 feat: add navbar + hero section; the navbar and the hero are responsive
  hero.png
  index.html
Labels: enhancement

#6 feat: Make the `hero.png` image transparent
  hero.png
Labels: enhancement

#7 feat: Improve the pull request template
  .github/pull_request_template.md
Labels: documentation

#8 Add Contributor Covenant Code of Conduct v2.1
  CODE_OF_CONDUCT.md
Labels: enhancement

#9 feat: Add a favicon to the website
  favicon.ico
  index.html
Labels: enhancement

#12 feat: add footer design and first section
  index.html
  logo.png
Labels: enhancement

#13 [feat/fix]: Make the `hero.png` image size bigger
  hero.png
Labels: enhancement

#16 feat: add 'Blockchain Developer Path' section
  assets/favicon.ico
  assets/framer.png
  assets/hero.png
  assets/logo.png
  assets/mindmaster.png
  assets/whimsical.png
  assets/zapier.png
  index.html
Labels: enhancement

#22 fix: minor spelling typo
  index.html
Labels: enhancement

#23 [feat/fix]: Implement changes from a pending review
  index.html
Labels: enhancement

#25 add a emoji in footer
  index.html
Labels: enhancement

#19 feat: make the cards clickable
  index.html
Labels: enhancement

#29 fix: make each cards clickable instead of parent section
  index.html
Labels: enhancement

#32 feat: Add Community blogs
  assets/blogs_figma.png
  assets/blogs_inVision.png
  assets/blogs_xd.png
  index.html
Labels: enhancement

#34 BLOG added in the navbar web3community#33
  index.html
Labels: enhancement

#39 Add Dev protocol brand section
  assets/dev_protocol.png
  assets/dev_protocol_forum.png
  assets/stakes_social.png
  index.html
Labels: enhancement

#40 feat: add testimonial section
  assets/placeholder/placeholder_1.png
  assets/placeholder/placeholder_2.png
  assets/placeholder/placeholder_3.png
  index.html
Labels: enhancement

#44 :lipstick: Reduce main title size
  index.html
Labels: enhancement

#48 Navbar was covering Page content | Fixed
  index.html
Labels: enhancement

#55 feat: Add basic issue forms
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: enhancement

#54 [FEAT] - Alpine (N)EAT stack starter
  .eleventy.js
  .eleventyignore
  .github/workflows/eleventy_build.yml
  .gitignore
  .nojekyll
  README.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/_data/navigation.yaml
  src/_data/settings.yaml
  src/_includes/default.html
  src/_includes/partials/footer.html
  src/_includes/partials/navbar.html
  src/index.html
  src/static/css/tailwind.css
  src/static/img/blogs_figma.png
  src/static/img/blogs_inVision.png
  src/static/img/blogs_xd.png
  src/static/img/dev_protocol.png
  src/static/img/dev_protocol_forum.png
  src/static/img/favicon.ico
  src/static/img/framer.png
  src/static/img/hero.png
  src/static/img/icon.svg
  src/static/img/logo.png
  src/static/img/mindmaster.png
  src/static/img/placeholder/placeholder_1.png
  src/static/img/placeholder/placeholder_2.png
  src/static/img/placeholder/placeholder_3.png
  src/static/img/stakes_social.png
  src/static/img/whimsical.png
  src/static/img/zapier.png
  tailwind.config.js
Labels: documentation, enhancement, 🟪 priority: none
