Repository WebXDAO/WebXDAO.github.io, pull requests merged in 2021-10, with the labels that each got.

#61 Make Website Responsive
  package-lock.json
  src/_includes/partials/footer.html
  src/index.html
Labels: hacktoberfest-accepted, awaiting review

#65 Changed card content of blockchain dev path
  src/index.html
  src/static/img/cryptozombie.png
  src/static/img/figment.png
  src/static/img/simplilearn.png
  src/static/img/whiteboard.png
Labels: enhancement, hacktoberfest-accepted

#64 Add hamburger icon animation
  src/_includes/partials/navbar.html
  tailwind.config.js
Labels: hacktoberfest-accepted, awaiting review

#66 fix: Update social media text to `Socials`
  src/_includes/partials/footer.html
Labels: enhancement, hacktoberfest-accepted

#69 Issue #67 [FEATURE] Balance resources section
  src/_includes/partials/footer.html
Labels: enhancement, hacktoberfest-accepted

#72 [BUG] Update footer links on mobile
  src/_includes/partials/footer.html
Labels: enhancement, hacktoberfest-accepted

#80 Push date/author to the bottom of blog card
  src/blog/index.html
Labels: hacktoberfest-accepted

#121 fix: Update mail to the correct/new one
  CODE_OF_CONDUCT.md
  src/_includes/partials/footer.html
Labels: bug
