Repository WebXDAO/WebXDAO.github.io, pull requests merged in 2022-10, with the labels that each got.

#204 Add SEO Optimization
  next-seo.config.js
  package-lock.json
  package.json
  src/pages/_app.js
  src/pages/blog.js
  src/pages/index.js
  src/pages/moderators.js
  src/pages/partners.js
  src/pages/projects.js
Labels: enhancement, hacktoberfest-accepted

#201 [Bug] Fixed logo not redirecting to '/' (homepage)
  src/components/Global/Navbar.js
Labels: bug, hacktoberfest-accepted

#208 dx: Dockerfile added
  Dockerfile
  docker-compose.yaml
Labels: enhancement, hacktoberfest-accepted

#212 fix: accessibility issues on homepage
  src/components/Global/Footer.js
  src/components/Home/HeroSection/ContributeButton.js
  src/components/Home/HeroSection/DiscordButton.js
  src/pages/_document.js
Labels: bug, hacktoberfest-accepted

#213 docs: minor grammatical error fix
  src/components/Home/HeroSection/Hero.js
Labels: documentation

#215 chore: Added Metadata in package.json
  package.json
Labels: enhancement

#203 Hacktoberfest-2022 Contributors page
  src/components/Global/Navbar.js
  src/pages/contributors.js
Labels: enhancement, hacktoberfest-accepted

#210 Hacktoberfest-2022 Update blog page
  src/pages/blog.js
Labels: enhancement, hacktoberfest-accepted

#223 chore: add `autoprettier` github action
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/autoprettier.yaml
  .github/workflows/deploy-node.yml
  .prettierrc
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  package-lock.json
  package.json
  postcss.config.js
  src/components/Global/Blogs.jsx
  src/components/Global/Navbar.js
  src/components/Home/DeveloperPath.jsx
  src/components/Home/DevprotocolBrands.jsx
  src/components/Home/HeroSection/ContributeButton.js
  src/components/Home/HeroSection/DiscordButton.js
  src/components/Home/HeroSection/Hero.js
  src/components/Home/HeroSection/Hero2.js
  src/components/Home/Projects.jsx
  src/components/Home/Testimonials.jsx
  src/constants/index.js
  src/layouts/WebXLayout.js
  src/pages/_app.js
  src/pages/_document.js
  src/pages/api/hello.js
  src/pages/blog.js
  src/pages/contributors.js
  src/pages/index.js
  src/pages/moderators.js
  src/pages/partners.js
  src/pages/projects.js
  src/styles/globals.css
  tailwind.config.js
Labels: enhancement, In-Discussion

#225 added meta data
  src/pages/index.js
Labels: enhancement

#227 [FEAT]: add github contributors in the README
  README.md
Labels: documentation, enhancement

#235 FEAT: Home hyperlink fix
  src/components/Global/Footer.js
  src/components/Global/Navbar.js
Labels: bug

#220 Add About-us.js
  src/components/Home/AboutSection.js
  src/pages/about-us.js
Labels: enhancement

#245 Fixed the navbar logo bug for small screen
  src/components/Global/Footer.js
  src/components/Global/Navbar.js
Labels: bug

#254 fix: docker compose file
  docker-compose.yaml
Labels: bug
