Repository WebXDAO/WebXDAO.github.io, pull requests merged in 2023-05, with the labels that each got.

#272 discord invitation link updated
  src/components/Global/Footer.js
  src/components/Home/HeroSection/DiscordButton.js
Labels: documentation

#288 Update Project Folder Name
  backup src/components/Projects/ RepoCard.js
Labels: GSSoC23

#298 Added headline,blurbs and partners section as per v3 figma design
  app/page.tsx
  components/icons.tsx
  public/Arrow1.png
  public/Dev-protocol-1.png
  public/Lumos-Labs-1.png
  public/The-Algorithms-1.png
Labels: gssoc23, level3

#304 updating NextJs to stable version for stable app router
  package-lock.json
  package.json
Labels: gssoc23, level1

#309 Fixing ESlint Error
  app/blogs/page.tsx
  app/page.tsx
  components/v1/Global/Blogs.jsx
  components/v1/Global/Footer.js
  components/v1/Global/Navbar.js
  components/v1/Home/AboutSection.js
  components/v1/Home/DeveloperPath.jsx
  components/v1/Home/DevprotocolBrands.jsx
  components/v1/Home/HeroSection/CallToActionHero.js
  components/v1/Home/HeroSection/ContributeButton.js
  components/v1/Home/HeroSection/DiscordButton.js
  components/v1/Home/HeroSection/Hero.js
  components/v1/Home/HeroSection/Hero2.js
  components/v1/Home/Projects.jsx
  components/v1/Home/Testimonials.jsx
  components/v1/Projcts/ RepoCard.js
Labels: in review, gssoc23

#313 Updating GitHub & Twitter profile links
  config/site.ts
Labels: gssoc23, level1

#315 Fix : issue #311
  app/page.tsx
  config/site.ts
Labels: gssoc23, level1

#324 fixing partners issues
  app/page.tsx
  components/containers/Partners.tsx
  public/The-Algorithms-1.png
Labels: gssoc23, level2

#322 Adding export script in package.json
  next.config.mjs
  package-lock.json
  package.json
Labels: enhancement, gssoc23, level1

#328 ADD: FOOTER SECTION FOR V3 REBRANDING WEBSITE
  app/page.tsx
  components/site-header.tsx
  config/site.ts
  next.config.mjs
Labels: bug

#325 ADD : System Mode for light / dark theme
  components/theme-toggle.tsx
  styles/globals.css
Labels: bug, gssoc23, level2

#335 Added the Scroll to top nav button
  app/page.tsx
  components/ui/TopButton.css
  components/ui/TopButton.tsx
  package-lock.json
  package.json
Labels: gssoc23, level2

#337 Gradient Heading
  app/page.tsx
  components/containers/Partners.tsx
Labels: gssoc23, level2

#340 Solved Issue #323 [FEATURE] Add Contributors Page [GSSOC'23]
  app/contributors/page.tsx
  components/ContributorCard.tsx
  lib/fonts.ts
  public/fonts/gilroy/Gilroy-Black.ttf
  public/fonts/gilroy/Gilroy-BlackItalic.ttf
  public/fonts/gilroy/Gilroy-Bold.ttf
  public/fonts/gilroy/Gilroy-BoldItalic.ttf
  public/fonts/gilroy/Gilroy-ExtraBold.ttf
  public/fonts/gilroy/Gilroy-ExtraBoldItalic.ttf
  public/fonts/gilroy/Gilroy-Heavy.ttf
  public/fonts/gilroy/Gilroy-HeavyItalic.ttf
  public/fonts/gilroy/Gilroy-Light.ttf
  public/fonts/gilroy/Gilroy-LightItalic.ttf
  public/fonts/gilroy/Gilroy-Medium.ttf
  public/fonts/gilroy/Gilroy-MediumItalic.ttf
  public/fonts/gilroy/Gilroy-Regular.ttf
  public/fonts/gilroy/Gilroy-RegularItalic.ttf
  public/fonts/gilroy/Gilroy-SemiBold.ttf
  public/fonts/gilroy/Gilroy-SemiBoldItalic.ttf
  public/fonts/gilroy/Gilroy-Thin.ttf
  public/fonts/gilroy/Gilroy-ThinItalic.ttf
  public/fonts/gilroy/Gilroy-UltraLight.ttf
  public/fonts/gilroy/Gilroy-UltraLightItalic.ttf
  public/fonts/gilroy/License.txt
  public/hand-shake.svg
Labels: gssoc23, level3

#354 #347:Add a feature to hover on card items
  components/containers/Partners.tsx
Labels: gssoc23, level1

#346 Changes GitHub to Guild.xyz
  app/page.tsx
  components/icons.tsx
  config/site.ts
  public/guild-logo.png
Labels: gssoc23, level1

#363 #348-mobile navbar fixed
  components/main-nav.tsx
  components/site-header.tsx
Labels: gssoc23, level2

#371 fixing navbar width issue
  components/main-nav.tsx
Labels: gssoc23, level1

#369 Adding footer and scroll to top button on every page
  app/layout.tsx
  app/page.tsx
  components/Footer.tsx
  components/main-nav.tsx
  components/site-header.tsx
Labels: gssoc23, level1

#370 fixing heading responsive issue
  app/page.tsx
  components/containers/Partners.tsx
Labels: gssoc23, level1

#380 updated the readme file with better installation guidelines
  README.md
Labels: gssoc23, level1

#373 Automatic year update in Copyright section
  app/page.tsx
Labels: gssoc23, level1

#394 docs: update issue form templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: documentation, gssoc23

#375 Solved Issue #341 [FEATURE] Create Updated Navbar based on V3 design files [GSSoC'23]
  components/main-nav.tsx
  components/site-header.tsx
  public/logo-v3-full-dark.png
  public/logo-v3-full.png
Labels: gssoc23, level1, level2

#388 refactoring landing page code
  app/contributors/page.tsx
  app/page.tsx
  components/Footer.tsx
  components/landing/Blurbs.tsx
  components/landing/Main.tsx
  components/landing/Partners.tsx
  public/The-Algorithms-1.png
Labels: level2
