Repository WebXDAO/WebXDAO.github.io, pull requests merged in 2023-06, with the labels that each got.

#409 💡 [FEAT]: ACCESSIBLE SOCIAL ANCHORS W/ A11Y PRINCIPLES
  components/Footer.tsx
  components/main-nav.tsx
Labels: gssoc23, level1

#406 [OTHER] Used main in the license badge link
  README.md
Labels: enhancement

#419 chore: link to Lumos Labs website
  components/landing/Partners.tsx
Labels: enhancement

#405 fix: `package.json` meta
  package.json
Labels: enhancement

#429 Used new Discord invitation link
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#426 docs: add the forking step in `README.md`
  README.md
Labels: documentation

#417 adding gap between navbar and main content
  components/landing/Main.tsx
Labels: enhancement, gssoc23, level1

#432 fix: remake project card with reg. to v3 design
  app/projects/page.tsx
  components/ProjectCard.tsx
Labels: gssoc23, level2

#420 feat: Added the WebXTeam page
  app/teams/page.tsx
  components/TeamCard.tsx
Labels: enhancement, In-Discussion, gssoc23, level3

#411 Added custom scrollbar
  styles/globals.css
Labels: enhancement, gssoc23, level2

#440 Error Page Added
  app/not-found.tsx
  public/Frame.png
Labels: gssoc23, level3

#444 using src directory For Improving Code Organization
  src/app/blogs/page.tsx
  src/app/contributors/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/projects/page.tsx
  src/app/teams/page.tsx
  src/components/ContributorCard.tsx
  src/components/Footer.tsx
  src/components/ProjectCard.tsx
  src/components/TeamCard.tsx
  src/components/cursor-hoverster.tsx
  src/components/icons.tsx
  src/components/landing/Blurbs.tsx
  src/components/landing/Main.tsx
  src/components/landing/Partners.tsx
  src/components/layout.tsx
  src/components/main-nav.tsx
  src/components/site-header.tsx
  src/components/star.tsx
  src/components/tailwind-indicator.tsx
  src/components/theme-provider.tsx
  src/components/theme-toggle.tsx
  src/components/ui/TopButton.css
  src/components/ui/TopButton.tsx
  src/components/ui/button.tsx
  src/components/v1/Global/Blogs.jsx
  src/components/v1/Global/Footer.js
  src/components/v1/Global/Navbar.js
  src/components/v1/Home/AboutSection.js
  src/components/v1/Home/DeveloperPath.jsx
  src/components/v1/Home/DevprotocolBrands.jsx
  src/components/v1/Home/HeroSection/CallToActionHero.js
  src/components/v1/Home/HeroSection/ContributeButton.js
  src/components/v1/Home/HeroSection/DiscordButton.js
  src/components/v1/Home/HeroSection/Hero.js
  src/components/v1/Home/HeroSection/Hero2.js
  src/components/v1/Home/Projects.jsx
  src/components/v1/Home/Testimonials.jsx
  src/components/v1/Projcts/_RepoCard.js
  src/config/site.ts
  src/lib/fonts.ts
  src/lib/utils.ts
  src/styles/globals.css
  src/types/nav.ts
  tailwind.config.js
  tsconfig.json
Labels: gssoc23, level3

#453 Exceeding width
  src/app/projects/page.tsx
Labels: gssoc23, level1

#458 changing placement of hamburger to right
  src/components/main-nav.tsx
Labels: gssoc23, level1
