Repository WebXDAO/WebXDAO.github.io, pull requests merged in 2023-07, with the labels that each got.

#457 card widths in Blurb section
  src/components/landing/Blurbs.tsx
Labels: gssoc23, level2

#464 adding event listener to close navbar dropdown
  src/components/main-nav.tsx
Labels: gssoc23, level2

#469 [ADDED]: sitemap.xml
  public/sitemap.xml
Labels: enhancement

#475 fix: `teams` -> `team`
  src/app/team/page.tsx
  src/app/teams/README.md
  src/app/teams/page.tsx
  src/config/site.ts
Labels: enhancement

#478 adding title to every page
  src/app/blogs/page.tsx
  src/app/contributors/page.tsx
  src/app/projects/page.tsx
  src/app/team/page.tsx
Labels: awaiting review, gssoc23

#474 feat: add CODEOWNERS and fix blog page error
  .github/CODEOWNERS
  next.config.mjs
  src/app/blogs/Blog.tsx
  src/app/blogs/page.tsx
  src/lib/utils.ts
Labels: enhancement, in review, In-Discussion
